prod:
  config_name: Prod
  inherits: test
  quarto-pubs-id: 7fb37ad4-6649-48a7-a989-83dfa5391e65
  quarto-pubs-url: https://alexkgold.quarto.pub/palmer-penguins-report/

test:
  config_name: Test
  line_color: orange

default:
  config_name: Dev
  line_color: purple
  quarto-pubs-id: 17ec82c7-ba70-4df8-85c2-b94c1e1b8aad
  quarto-pubs-url: https://alexkgold.quarto.pub/palmer-penguins-report-test/

